Repository vhive-serverless/vHive, pull requests merged in 2021-06, with the labels that each got.

#258 Hotfix: Set scripts/disable_auto_updates.sh executable bit
  scripts/cloudlab/setup_node.sh
  scripts/utils/disable_auto_updates.sh
Labels: bug

#269 Contributing to vHive document
  README.md
  configs/.wordlist.txt
  docs/contributing_to_vhive.md
Labels: documentation

#251 Add knative-eventing-tutorial example
  CHANGELOG.md
  configs/.wordlist.txt
  docs/knative/assets/broker-topology.drawio
  docs/knative/assets/broker-topology.png
  docs/knative/assets/broker.png
  docs/knative/assets/channel-topology.drawio
  docs/knative/assets/channel-topology.png
  docs/knative/assets/channel.drawio
  docs/knative/assets/channel.png
  docs/knative/eventing.md
  examples/knative-eventing-tutorial/.gitignore
  examples/knative-eventing-tutorial/Dockerfile
  examples/knative-eventing-tutorial/Makefile
  examples/knative-eventing-tutorial/README.md
  examples/knative-eventing-tutorial/cmd/eventschemas.go
  examples/knative-eventing-tutorial/cmd/overheatConsumer/main.go
  examples/knative-eventing-tutorial/cmd/server/main.go
  examples/knative-eventing-tutorial/cmd/server/tempReader.pb.go
  examples/knative-eventing-tutorial/cmd/server/tempReader.proto
  examples/knative-eventing-tutorial/cmd/server/tempReader_grpc.pb.go
  examples/knative-eventing-tutorial/cmd/tempConsumer/main.go
  examples/knative-eventing-tutorial/config-k8s.yaml
  examples/knative-eventing-tutorial/config-kn.yaml
  examples/knative-eventing-tutorial/go.mod
  examples/knative-eventing-tutorial/go.sum
Labels: documentation

#271 Adds vhiveease/golang workflow
  .github/workflows/image_build.yml
  configs/golang/Dockerfile
Labels: enhancement

#284 fix commitlinter to fail on unsigned commit
  configs/commitlint.config.js
Labels: bug

#294 add instructions to use private Go modules
  configs/.wordlist.txt
  docs/contributing_to_vhive.md
Labels: documentation

#302 Added tracing screenshots
  docs/benchmarking/adding_benchmarks.md
  docs/figures/tracing_breakdown.jpg
  docs/figures/tracing_chain_view.jpg
Labels: bug

#309 Clarified how to run a vHive cluster in a kind container
  docs/developers_guide.md
Labels: documentation
