Repository vhive-serverless/vHive, pull requests merged in 2021-05, with the labels that each got.

#243 Updated to the recommended Cloudlab profile
  configs/.wordlist.txt
  docs/quickstart_guide.md
Labels: bug, documentation

#252 Improve setup_nodes.sh
  scripts/cloudlab/setup_node.sh
  scripts/disable_auto_updates.sh
  scripts/install_stock.sh
  scripts/setup_system.sh
Labels: enhancement

#259 Pin Knative to v0.21.0
  scripts/install_stock.sh
Labels: bug
