Repository vhive-serverless/vHive, pull requests merged in 2021-01, with the labels that each got.

#93 Update and fix nightly test schedule
  .github/workflows/nightly_tests.yml
Labels: bug

#95 Increase startVM timeout value
  functions.go
Labels: enhancement

#103 Developer's guide extended with performance analysis description
  README.md
  docs/developers_guide.md
  docs/quickstart_guide.md
  examples/README.md
Labels: documentation

#104 Added references to the ASPLOS'21 paper and the paper itself
  README.md
  docs/papers/REAP_ASPLOS21.pdf
  docs/quickstart_guide.md
Labels: documentation
